# Generated by Django 3.2.4 on 2021-06-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=250)),
                ('product_code', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(max_length=50)),
                ('brand', models.CharField(default='', max_length=250)),
                ('expire_date', models.DateField(null=True)),
            ],
        ),
    ]
