# Generated by Django 3.2.4 on 2021-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field= models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='expire_date',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
