# Generated by Django 3.2.4 on 2021-06-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210609_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.CharField(default='', max_length=250),
        ),
    ]
